export const slides = [
  {
    cover: true,
    title: 'AccessRide',
    subtitle: 'Accessible Transportation and Emergency Coordination',
    bullets: [],
    narration: 'AccessRide connects people with disabilities and transportation agencies through two coordinated applications for ride requests, live status updates, emergency assistance, and continued account support.',
  },
  {
    title: 'AccessRide',
    subtitle: 'Accessible transportation. Connected support.',
    bullets: ['Rider mobile app', 'Agency operations app', 'Real-time trip and SOS coordination'],
    narration: 'AccessRide is a two-app transportation and safety platform designed for people with disabilities and the government or community agencies that serve them. This presentation shows the complete workflow using the real Rider and Agency interfaces.',
  },
  {
    title: 'Why AccessRide Matters',
    subtitle: 'Transportation access supports independent living.',
    bullets: [
      'More than 1 in 4 U.S. adults has a disability',
      '18.6 million Americans report travel-limiting disabilities',
      'Reliable transportation and timely assistance remain essential',
    ],
    footnote: 'Sources: CDC Disability and Health; U.S. DOT Bureau of Transportation Statistics.',
    narration: 'More than one in four adults in the United States has a disability. The U.S. Department of Transportation estimates that 18.6 million Americans age five and older have a condition that limits travel. Reliable transportation is essential for medical visits, employment, services, shopping, and community life.',
  },
  {
    title: 'One Connected Service, Two Apps',
    subtitle: 'Each user sees the tools needed for their role.',
    bullets: [
      'Rider app: request rides, track status, update password, send SOS',
      'Agency app: manage riders, dispatch trips, respond to emergencies',
      'Shared cloud database keeps both sides synchronized',
    ],
    narration: 'AccessRide separates the experience into two secure applications. Riders receive a simple, accessible interface. Agency staff receive an operational dashboard for many riders. Both apps use the same cloud service, so ride status and emergency alerts remain synchronized across devices.',
  },
  {
    title: 'Step 1: Rider Sign-In',
    subtitle: 'The rider uses the account created by the agency.',
    image: '01-rider-login.png',
    bullets: ['Enter the assigned username', 'Enter the temporary or current password', 'Account access is limited to that rider’s information'],
    narration: 'The process begins when the rider signs in with the username and password provided by the agency. The account connects the rider to the correct agency and profile. After signing in, the rider can access transportation requests, ride status, safety tools, and account settings.',
  },
  {
    title: 'Rider Home Screen',
    subtitle: 'The most important actions are visible immediately.',
    image: '02-rider-home.png',
    bullets: ['Request a ride', 'Open the SOS control', 'Review upcoming rides', 'Switch language or open the profile'],
    narration: 'The Rider home screen keeps the primary actions large and easy to find. The rider can begin a transportation request, access the emergency panel, review upcoming rides, change language, open the profile, or reach support without navigating through complicated menus.',
  },
  {
    title: 'Step 2: Enter a Round Trip',
    subtitle: 'Detailed information helps the agency schedule correctly.',
    image: '03-round-trip-request.png',
    bullets: ['Pickup and destination', 'Travel date and outbound pickup time', 'Return pickup time', 'Wheelchair, walker, service animal, or boarding assistance'],
    narration: 'To request transportation, the rider selects one way or round trip. For a round trip, the rider enters the pickup address, destination, travel date, outbound time, and return pickup time. Accessibility requirements can also be included so the agency can assign an appropriate vehicle and assistance.',
  },
  {
    title: 'Voice Input and Request Submission',
    subtitle: 'Addresses and accessibility needs can be entered by voice.',
    image: '03-round-trip-request.png',
    bullets: ['Microphone controls support voice entry', 'Required fields are clearly marked', 'Send Request submits the trip to the agency'],
    narration: 'Each major text field includes a microphone control for riders who prefer voice input. Required fields are clearly marked. When the information is complete, the rider selects Send Request. The trip is written to the shared cloud database and becomes available to authorized agency staff.',
  },
  {
    title: 'Request Confirmation',
    subtitle: 'The rider immediately sees the submitted trip.',
    image: '04-rider-requested.png',
    bullets: ['Initial status: Requested', 'Date, time, route, and accessibility needs remain visible', 'The rider can return to change the ride'],
    narration: 'After submission, the rider sees the trip in My Rides with a Requested status. The route, date, pickup time, return details, and accessibility needs remain visible for review. Before service is completed, the rider can reopen the request and make necessary changes.',
  },
  {
    title: 'Step 3: Agency Receives the Request',
    subtitle: 'New requests appear in the transportation queue.',
    image: '06-agency-new-request.png',
    bullets: ['Agency dashboard updates from the shared database', 'Staff can review rider and accessibility information', 'Pending requests are visible in one operational queue'],
    narration: 'The Agency app receives the new trip from the same cloud database. Dispatch staff can see the rider, pickup, destination, requested time, and accessibility needs. Pending requests are organized in a shared queue so the agency can coordinate service for multiple riders.',
  },
  {
    title: 'Agency Accepts the Ride',
    subtitle: 'One action changes the request from Requested to Scheduled.',
    image: '07-agency-scheduled.png',
    bullets: ['Select Accept', 'Status changes to Scheduled', 'The updated status is shared with the rider'],
    narration: 'An authorized staff member reviews the details and selects Accept. The trip status changes from Requested to Scheduled. Because the applications are synchronized, this is not only an internal agency update. The new status becomes available to the rider as well.',
  },
  {
    title: 'Agency Assigns a Driver',
    subtitle: 'Dispatch can continue moving the ride through service.',
    image: '08-agency-driver-assigned.png',
    bullets: ['Select Assign Driver', 'Status changes to Driver Assigned', 'Later, staff can mark the ride Completed'],
    narration: 'When transportation is arranged, dispatch selects Assign Driver. The status changes to Driver Assigned. The same workflow can later mark the trip Completed. These clear stages help staff understand operational progress and help riders know what is happening without calling for routine updates.',
  },
  {
    title: 'Step 4: Rider Sees Live Status',
    subtitle: 'The rider can follow the agency’s progress.',
    image: '09-rider-status-update.png',
    bullets: ['Requested', 'Scheduled', 'Driver Assigned', 'Completed'],
    narration: 'In the Rider app, My Rides reflects the agency’s latest status. The rider can see whether the request is waiting for review, scheduled, assigned to a driver, or completed. This shared visibility reduces uncertainty and helps the rider prepare for pickup.',
  },
  {
    title: 'Step 5: Rider Activates SOS',
    subtitle: 'Press and hold to reduce accidental activation.',
    image: '10-rider-sos.png',
    bullets: ['Long-press SOS', 'Share available location information', 'Receive confirmation that dispatch received the alert'],
    narration: 'If the rider needs urgent assistance, the SOS button is pressed and held. The hold interaction helps prevent accidental alerts. AccessRide sends the rider identity, time, and available location to the agency, then confirms on screen that dispatch received the SOS.',
  },
  {
    title: 'Agency Responds to SOS',
    subtitle: 'The alert appears immediately on the dispatch dashboard.',
    image: '11-agency-sos-call.png',
    bullets: ['Visible Active SOS alert', 'Rider name, time, and location', 'Call Rider and Acknowledge actions'],
    narration: 'The agency sees an Active SOS alert with the rider’s name, event time, and location when available. Staff can select Call Rider to return the call immediately, coordinate assistance, and then acknowledge the alert so the team knows it is being handled.',
  },
  {
    title: 'Emergency Safety Boundary',
    subtitle: 'AccessRide supports agency response but does not replace 911.',
    image: '10-rider-sos.png',
    bullets: ['Call 911 for immediate danger', 'SOS alerts the transportation agency', 'The rider app provides a direct 911 call action'],
    narration: 'AccessRide SOS is an agency assistance channel, not a replacement for emergency services. The Rider app clearly instructs users to call 911 when there is immediate danger and provides a direct Call 911 action. This distinction is essential for responsible deployment.',
  },
  {
    title: 'Agency Manages Rider Accounts',
    subtitle: 'The agency maintains the list of people it serves.',
    image: '12-rider-directory.png',
    bullets: ['Search rider records', 'Review contact and accessibility needs', 'Activate or deactivate an account', 'Open password recovery'],
    narration: 'The Riders area gives the agency a central directory of the people it serves. Staff can search records, review contact information and accessibility requirements, activate or deactivate an account, and begin password recovery when a rider cannot sign in.',
  },
  {
    title: 'Create a New Rider',
    subtitle: 'Staff creates the profile and initial credentials.',
    image: '14-agency-create-rider.png',
    bullets: ['Name, birth date, phone, and address', 'Emergency contact and accessibility needs', 'Unique username and temporary password'],
    narration: 'To enroll a new rider, agency staff creates the base profile. The form includes identity and contact information, emergency contact details, accessibility needs, communication preference, a unique username, and a temporary password. Birth year, month, and day can be selected directly.',
  },
  {
    title: 'Password Management',
    subtitle: 'Riders control their password; agencies can assist with recovery.',
    image: '15-rider-change-password.png',
    secondaryImage: '13-agency-reset-password.png',
    bullets: ['Rider changes the password after signing in', 'Agency can issue a temporary password after confirming recovery', 'Only authorized staff can reset accounts in their agency'],
    narration: 'After receiving the initial credentials, the rider can open My Profile and change the password by entering the current password and a new one. If the rider forgets the password, authorized agency staff can confirm the recovery request and issue a new temporary password.',
  },
  {
    title: 'AccessRide',
    subtitle: 'Reliable rides. Faster response. Greater independence.',
    bullets: [
      'Accessible rider experience',
      'Coordinated agency operations',
      'Real-time trip status and SOS response',
      'Account tools for continued service',
    ],
    narration: 'AccessRide brings transportation requests, agency coordination, status visibility, emergency assistance, and account management into one connected service. The goal is practical: reduce barriers, support independent living, and help agencies respond with clearer information and greater speed.',
  },
]
